#!/bin/bash

if [ "$#" -ne "2" ]
  then
    echo "No arguments supplied. Call using $0 <MINER_NAME> <MINER_URL>"
    exit
fi

miner_name=$1
miner_url=$2
miner_dir="/hive/miners/$miner_name"
current_version=$(ls -d $miner_dir/*/ | xargs -n 1 basename | sort -V | tail -1)
echo Current $miner_name version - $current_version
curl -s -L $miner_url | tar xz -C $miner_dir/$current_version --strip-components 1

if [ $? -eq 0 ]; then
    echo $miner_name has been updated successfully.
else
    echo Oops! Something went wrong. Please try again.
fi
